# Generated by Django 2.2.1 on 2019-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_database',
            fields=[
                ('employee_code', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('Father_or_Husband_name', models.CharField(max_length=264)),
                ('Company_name', models.CharField(max_length=264)),
                ('dob', models.DateField()),
                ('Gender', models.CharField(max_length=264)),
                ('location', models.CharField(max_length=264)),
                ('PAN', models.CharField(max_length=264)),
                ('Contact_Number', models.CharField(max_length=264)),
                ('Date_of_Join', models.DateField()),
            ],
        ),
    ]
