# Generated by Django 2.2.2 on 2019-06-17 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment_bot', '0002_auto_20190617_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_database',
            name='Date_of_Join',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_database',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
