# Generated by Django 2.2.1 on 2019-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_bot', '0003_auto_20190617_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=100)),
                ('subsection_id', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=10000)),
            ],
            options={
                'unique_together': {('section_id', 'subsection_id')},
            },
        ),
    ]
