# Generated by Django 2.2.1 on 2019-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_bot', '0005_amount_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('employee_code', models.CharField(max_length=100)),
                ('section_id', models.CharField(max_length=100)),
                ('subsection_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
